src/Entity/Comment.php
<?php

namespace App\Entity;

use App\Repository\CommentRepository;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Timestampable\Traits\TimestampableEntity;

#[ORM\Entity(repositoryClass: CommentRepository::class)]
class Comment
{
    use TimestampableEntity;
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id ;

    #[ORM\ManyToOne(inversedBy: 'comments')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Post $Post;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    private ?Account $Account;

    #[ORM\Column(length: 255)]
    private ?string $commentText;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPost(): ?Post
    {
        return $this->Post;
    }

    public function setPost(?Post $Post): self
    {
        $this->Post = $Post;

        return $this;
    }

    public function getAccount(): ?Account
    {
        return $this->Account;
    }

    public function setAccount(?Account $Account): self
    {
        $this->Account = $Account;

        return $this;
    }

    public function getCommentText(): ?string
    {
        return $this->commentText;
    }

    public function setCommentText(string $commentText): self
    {
        $this->commentText = $commentText;

        return $this;
    }
}

templates/Macros/comment.twig
{% macro comment(comment) %}
    <div class="card-comment">
        <!-- User image -->
        <a href="{{ path('profile_page_view', {'id': comment.account.id}) }}">
            <img alt="User Image" class="img-circle img-sm" src="{{ asset(comment.account.getAvatarPath()) }}">
        </a>

        <div class="comment-text">
            <span class="username">
                <a href="{{ path('profile_page_view', {'id': comment.account.id}) }}">
                    {{ comment.account.getFullName }}
                </a>
                <span class="text-muted float-right">{{ comment.createdAt|ago }}</span>
            </span><!-- /.username -->
            {{ comment.commentText }}
            <div>
               <a href="{{ path('delete_comment', {'id': comment.id}) }}" class="btn btn-tool" onclick="return confirm('Are you sure you want to delete this comment?');" type="button">
        <i class="far fa-trash-alt"></i> Delete</a>
      
            <a href="{{ path('edit_comment', {'id': comment.id}) }}" class="btn btn-tool" onclick="return confirm('Are you sure you want to Edit this comment?');" type="button">
        <i class="far fa-edit"></i> Edit</a>
        </div>
         
        
</form>
        </div>
        <!-- /.comment-text -->
    </div>
{% endmacro %}

templates/Macros/post.twig
{% macro post(post, account) %}
    {% import 'Macros/comment.twig' as comment %}
    <div class="post" style="width: 100%">
        <div class="row">
            <div class="col-md-12">
                <!-- Box Comment -->
                <div class="card card-widget">
                    <div class="card-header">
                        <div class=" col-md-11 user-block">
                            <img alt="User Image" class="img-circle" src={{ asset(post.account.getAvatarPath()) }}>
                            <span class="username"><a href="{{ path('profile_page_view', {'id': post.account.id}) }}">{{ post.account.getFullName }}</a></span>
                            <span class="description">{{ post.createdAt|ago }}</span>
                        </div>
                        <div class=" col-md-1 card-tools d-flex justify-content-end">
                            <button class="btn btn-tool" data-card-widget="remove" type="button">
                                <a href="{{ path('delete_post', {'id': post.id}) }}" class="btn btn-tool" onclick="return confirm('Are you sure you want to delete this post?');" type="button">
                                <i class="fas fa-times"></i>
                                </a>
                            </button>
                        </div>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                        <div class="col-12">
                            <p>{{ post.text }}</p>
                            {% if post.photo %}
                                <img class="img-fluid pad" src="{{  asset(post.getPhotoPath()) }}" alt="Photo"
                                     style="margin-bottom: 1rem; margin-right: 2rem">
                            {% endif %}
                        </div>
                        <div class="col-12">
                            {% if post.likedBy.contains(app.user) %}
                                <a class="btn btn-sm btn-primary"  href ="{{ path('app_unlike',{id: post.id})}}" ><i class="fa-solid fa-thumbs-down"></i>unlike</a>
                            {% else %}
                                <a class="btn btn-sm btn-primary" href ="{{path('app_like',{id: post.id})}}" ><i class="far fa-thumbs-up"></i> like </a>
                            {% endif %}
                            {% if is_granted('ROLE_ADMIN') == true %}
 <a class="btn btn-warning btn-sm report-btn" href="#" data-account-id="{{ account.id }}">
            <i class="fas fa-flag"></i> Report
        </a>                            {% endif %}
                            <span class="float-right text-muted px-2"  id = "comments-count_{{ post.id }}" > {{ post.comments| length}}  comments</span>
                            <span class="float-right text-muted px-2 ">{{ post.likedBy.count}} likes </span>
                        </div>
                    </div>
                    <!-- /.card-body -->
                    <div class="card-footer card-comments comments_{{ post.id }}">
                        {% for comment in post.comments %}
                            {{ comment.comment(comment) }}
                        {% endfor %}
                    </div>
                    <!-- /.card-footer -->
                    <div class="card-footer">
                        <form id="formComment" action="{{ path('add_comment',{'id':post.id}) }}" method="post"  class="comment-form"  data-post-id = "{{ post.id }}">
                            <img alt="Alt Text" class="img-fluid img-circle img-sm" src="{{ asset(account.getAvatarPath()) }}">
                            <!-- .img-push is used to add margin to elements next to floating images -->
                            <div class="img-push">
                                <input class="form-control form-control-sm" placeholder="Press enter to post comment"  type="text" name="commentText">
                            </div>
                        </form>
                    </div>
                    <!-- /.card-footer -->
                </div>
                <!-- /.card -->
            </div>
        </div>
    </div>
     <script>
   $(document).ready(function() {
    $('.report-btn').click(function(e) {
        e.preventDefault();
        var accountId = $(this).data('account-id');
        
        $.ajax({
            url: '/report-account', 
            method: 'POST',
            data: { accountId: accountId },
            success: function(response, status, xhr) {
                if (xhr.status === 200) {
                    // Handle success
                    alert('Account reported successfully!');
                } else {
                    // Handle other status codes
                    console.error('Unexpected status code:', xhr.status);
                }
            },
            error: function(xhr, status, error) {
                console.error('Error reporting account:', error);
            }
        });
    });
});



</script>
  
{% endmacro %}

templates/Macros/profile.twig
{% macro profile (account) %}
    <div class="col-12 col-sm-6 col-md-4 d-flex align-items-stretch flex-column">
        <div class="card bg-light d-flex flex-fill">
            <div class="card-header text-muted border-bottom-0">
               {{ account.title }}
            </div>
            <div class="card-body pt-0">
                <div class="row">
                    <div class="col-7">
                        <h2 class="lead"><b>{{ account.getFullName }}</b></h2>
                        <ul class="ml-4 mb-0 fa-ul text-muted">
                            <li class="h6"><span class="fa-li"><i
                                            class="fas fa-lg fa-building"></i></span>
                                Address:
                                {{ account.address }}
                            </li>
                            <li class="small"><span class="fa-li"><i
                                            class="fas fa-lg fa-phone"></i></span> Phone
                                #: +
                                {{ account.phone }}
                            </li>
                        </ul>
                    </div>
                    <div class="col-5 text-center">
                        <img src="{{ account.getAvatarPath() }}" alt="" class="img-circle img-fluid">
                    </div>
                </div>
            </div>
            <div class="card-footer row">
                <div class="col-md-6 text-left">
                    {# <a href="" class="btn btn-sm btn-success">
                        <i class="fas fa-plus"></i> Follow
                    </a> #}
                        {{ include("follower/_follow_button.html.twig", {userToFollow: account}) }}

                </div>
                <div class="col-md-6 text-right">
                    <a href="{{ path('profile_page_view',{id: account.id}) }}" class="btn btn-sm btn-primary">
                        <i class="fas fa-user"></i> View Profile
                    </a>
                </div>
            </div>
        </div>
    </div>

{% endmacro %}